Merge bugfix/item-cannot-be-added-and-deleted-by-request branch
SeinekVoytov/E-Commerce-Microservices pull request #4
Opened 2024-06-19 14:40 UTC by SeinekVoytov

2024-06-26 06:17 UTC, dkisliak requested changes

2024-06-26 06:17 UTC, dkisliak commented on order-service/src/main/java/org/example/orderservice/controller/OrderController.java
> +@RequestMapping("/order")
Да orders же)
https://restfulapi.net/resource-naming/

2024-06-26 06:17 UTC, dkisliak commented on user-service/src/main/java/org/example/userservice/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorObject> handleNotFoundExceptions(Exception exc) {
Почему хэндлим прям Exception, а не конкретный?

2024-06-26 06:17 UTC, dkisliak commented on user-service/src/test/java/org/example/userservice/service/impl/CartServiceImplTest.java
> +                new HashSet<>(Set.of(cartItemResponse)),
new HashSet<>(Set.of(cartItemResponse))
 Так ли надо это?)
 Просто Set.of(cartItemResponse) не обойтись? Или потом эту коллекцию нужно изменять?

2024-06-27 13:50 UTC, SeinekVoytov commented on user-service/src/test/java/org/example/userservice/service/impl/CartServiceImplTest.java
> +                new HashSet<>(Set.of(cartItemResponse)),
Да, чтобы можно было потом ее изменять

2024-06-27 13:51 UTC, SeinekVoytov commented on user-service/src/main/java/org/example/userservice/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorObject> handleNotFoundExceptions(Exception exc) {
Exception, чтобы охватывать сразу все 3 исключения (ProductNotFoundException, CartItemNotFoundException, CartNotFoundException) в одном методе

2024-06-28 15:36 UTC, merged